### ISSUE TITLE
Error: specified lib dir does not exist: /usr/local/lib

### ISSUE THREAD

**Issue by Tenjin0** [justadudewhohacks/npm-opencv-build#11]
I'm on Windows 10 and i cannot install opencv4nodejs anymore.

When i try to do a npm i opencv4nodejs i got this message:

Error: specified lib dir does not exist: /usr/local/lib
    at Object.getLibs (C:\Users\...\plugins\Camera\node_modules\opencv-build\libs.js:39:13)
    at Object.<anonymous> (C:\...\plugins\Camera\node_modules\opencv4nodejs\lib\libs.js:12:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
gyp: Call to 'node ./lib/libs.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp

**Comment by justadudewhohacks** [comment]
The error message might be a bit confusing. You probably don't have OPENCV_LIB_DIR defined.
