### ISSUE TITLE
 Installation error

### ISSUE THREAD

**Issue by klaseca** [justadudewhohacks/npm-opencv-build#38]
```
684 verbose stack Error: opencv-build@0.1.9 install: `node ./install.js`
684 verbose stack Exit status 1
684 verbose stack     at EventEmitter.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
684 verbose stack     at EventEmitter.emit (events.js:189:13)
684 verbose stack     at ChildProcess.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
684 verbose stack     at ChildProcess.emit (events.js:189:13)
684 verbose stack     at maybeClose (internal/child_process.js:970:16)
684 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
685 verbose pkgid opencv-build@0.1.9
686 verbose cwd E:\Progaem\ocv
687 verbose Windows_NT 10.0.18362
688 verbose argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "opencv-build"
689 verbose node v10.15.1
690 verbose npm  v6.4.1
691 error code ELIFECYCLE
692 error errno 1
693 error opencv-build@0.1.9 install: `node ./install.js`
693 error Exit status 1
694 error Failed at the opencv-build@0.1.9 install script.
694 error This is probably not a problem with npm. There is likely additional logging output above.
695 verbose exit [ 1, true ]
```

**Comment by serena1234rex** [comment]
Same error, is there any solution？

ld: library not found for -lfreetype
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libopencv_freetype.3.4.6.dylib] Error 1
make[1]: *** [modules/freetype/CMakeFiles/opencv_freetype.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by albab** [comment]
Had the same error, found a solution here - https://github.com/justadudewhohacks/opencv4nodejs/issues/401#issuecomment-463542513

`brew uninstall tesseract`

**Comment by frank0820** [comment]
Im experiencing this error upon installation on windows. Can you help me?

> opencv-build@0.1.9 install C:\Users\franco\AppData\Roaming\npm\node_modules\opencv4nodejs\node_modules\opencv-build
> node ./install.js

info install if you want to use an own OpenCV installation set OPENCV4NODEJS_DISABLE_AUTOBUILD
info readAutoBuildFile file does not exists: C:\Users\franco\AppData\Roaming\npm\node_modules\opencv4nodejs\node_modules\opencv-build\opencv\auto-build.json C:\Users\franco\AppData\Roaming\npm\node_modules\opencv4nodejs\node_modules\opencv-build\opencv\auto-build.json
info install failed to find auto-build.json: C:\Users\franco\AppData\Roaming\npm\node_modules\opencv4nodejs\node_modules\opencv-build\opencv\auto-build.json
info install
info install running install script...
info install
info install opencv version: 3.4.6
info install with opencv contrib: yes
info install custom build flags:
info install
info install executing: git --version
info install git --version: git version 2.24.0.windows.2
info install
info install executing: cmake --version
info install cmake --version: cmake version 3.16.2
info install
info install CMake suite maintained and supported by Kitware (kitware.com/cmake).
info install
info install using msbuild: {
info install   path: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin\\MSBuild.exe',
info install   version: 15
info install }
ERR! Error: no cmake arch found for process.arch: ia32
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.1.9 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv-build@0.1.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\franco\AppData\Roaming\npm-cache\_logs\2020-01-16T11_19_55_610Z-debug.log

**Comment by endlesscpp** [comment]
I have the same problem on Windows side:

info install CMake suite maintained and supported by Kitware (kitware.com/cmake).
info install
info find-msbuild failed to find vs2017 via powershell: ʹ�á�0�����������á�Query��ʱ�����쳣:��� ��� COM �๤���� CLSID Ϊ {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} �����ʧ�ܣ�
info find-msbuild ԭ���ǳ������´���: 80040154 û��ע���� (�쳣���� HRESULT:0x80040154 (REGDB_E_CLASSNOTREG))����
info find-msbuild ����λ�� ��:1 �ַ�: 80
info find-msbuild + ... ncv-build\Find-VS2017.cs'; [VisualStudioConfiguration.Main]::Query()}
info find-msbuild +                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
info find-msbuild     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
info find-msbuild     + FullyQualifiedErrorId : COMException
info find-msbuild
info find-msbuild
info find-msbuild attempting to find msbuild via registry query...
info find-msbuild trying the following msbuild paths:
info find-msbuild version: 14, path: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
info find-msbuild version: 12, path: C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
info find-msbuild version: 4, path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
info install using msbuild: { version: 14,
info install   path: 'C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\msbuild.exe' }
ERR! Error: no cmake arch found for process.arch: ia32
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.1.9 install: `node ./install.js`
npm ERR! Exit status 1

**Comment by Calvin69** [comment]
Hello there! I'm on Windows and having this issue as well. Any solutions to it?

> opencv-build@0.1.9 install C:\WINDOWS\system32\node_modules\opencv-build
> node ./install.js

info install if you want to use an own OpenCV installation set OPENCV4NODEJS_DISABLE_AUTOBUILD
info readAutoBuildFile file does not exists: C:\WINDOWS\system32\node_modules\opencv-build\opencv\auto-build.json C:\WINDOWS\system32\node_modules\opencv-build\opencv\auto-build.json
info install failed to find auto-build.json: C:\WINDOWS\system32\node_modules\opencv-build\opencv\auto-build.json
info install
info install running install script...
info install
info install opencv version: 3.4.6
info install with opencv contrib: yes
info install custom build flags:
info install
info install executing: git --version
info install git --version: git version 2.23.0.windows.1
info install
info install executing: cmake --version
info install cmake --version: cmake version 3.20.0
info install
info install CMake suite maintained and supported by Kitware (kitware.com/cmake).
info install
info install using msbuild: {
info install   path: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin\\MSBuild.exe',
info install   version: 15
info install }
ERR! Error: no cmake arch found for process.arch: ia32
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.1.9 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv-build@0.1.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2021-04-08T09_07_13_533Z-debug.log

**Comment by giacomofuria** [comment]
I have the same problem on windows, someone solved it ? @Calvin69 You find a solution ?

**Comment by edmiester777** [comment]
@giacomofuria I ran into the same issue. If you run `node -p process.arch` it will show `ia32`. This means you've installed the intel 32-bit architecture version of nodejs. Just uninstall that one and pop a new `x64` one in its place. good as gold!

**Comment by nanchengjiumeng** [comment]
> @giacomofuria I ran into the same issue. If you run `node -p process.arch` it will show `ia32`. This means you've installed the intel 32-bit architecture version of nodejs. Just uninstall that one and pop a new `x64` one in its place. good as gold!

I know this, but my program used ia32.
